#!/usr/bin/env python3
"""
journal/build.py — turns bilingual Markdown blog posts into the site's
journal pages, in English AND German.

WHAT THIS DOES, IN PLAIN TERMS
  1. Reads every .md file in journal/posts-md/ (each one holds BOTH an
     English and a German version of the post — see journal-guide.md)
  2. Writes a matching styled HTML page for each one into journal/posts/,
     with the EN/DE toggle wired up and working
  3. Rewrites the post list on journal/index.html to match exactly those
     posts, in both languages
  4. Adds each post's title/lede/read-time to the auto-managed section of
     js/i18n.js, so the EN/DE header toggle can translate them
  5. Deletes any journal/posts/*.html page — and its js/i18n.js dictionary
     entries — that no longer has a matching .md file (so removing a post
     is just: delete the .md, rerun this script)

WHO SHOULD RUN THIS
  You, from a terminal, after adding/editing/deleting a .md file:
      python3 journal/build.py
  (Run it from anywhere — it finds its own folder automatically.)

See journal-guide.md (in the site root) for the full how-to, including the
Markdown/front-matter format this script expects and exactly how the
English/German split works.

WHY A SCRIPT INSTEAD OF HAND-WRITING HTML
  journal/posts/*.html is 100% generated by this file, and so is the
  BUILD:JOURNAL section of js/i18n.js. Never hand-edit either — your edits
  vanish the next time this runs, since the script treats
  journal/posts-md/*.md as the only source of truth for both.
"""
import html
import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent   # .../site
JOURNAL = SITE / "journal"
SRC_DIR = JOURNAL / "posts-md"
OUT_DIR = JOURNAL / "posts"
INDEX_FILE = JOURNAL / "index.html"
I18N_FILE = SITE / "js" / "i18n.js"

FILENAME_RE = re.compile(r"^(\d{4})-(\d{2})-(\d{2})-(.+)$")
GERMAN_SPLIT_RE = re.compile(r"^\s*\+\+\+\s*GERMAN\s*\+\+\+\s*$", re.M | re.I)
WORDS_PER_MINUTE = 200

# ---------------------------------------------------------------------------
# Front matter + Markdown parsing (a small, deliberately limited subset —
# see journal-guide.md for exactly what's supported and why).
# ---------------------------------------------------------------------------

def parse_front_matter(text, filename):
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n(.*)$", text, re.S)
    if not m:
        raise ValueError(
            f"{filename}: missing '---' front matter block at the top of the file. "
            f"See journal-guide.md for the required format."
        )
    raw_fm, rest = m.groups()
    fields = {}
    for i, line in enumerate(raw_fm.splitlines(), 1):
        if not line.strip():
            continue
        if ":" not in line:
            raise ValueError(f"{filename}: front matter line {i} has no ':' — {line!r}")
        key, _, value = line.partition(":")
        fields[key.strip().lower()] = value.strip()

    parts = GERMAN_SPLIT_RE.split(rest, maxsplit=1)
    if len(parts) != 2:
        raise ValueError(
            f"{filename}: couldn't find the '+++GERMAN+++' line that separates the "
            f"English body from the German body. Every post needs both — see "
            f"journal-guide.md."
        )
    body_en, body_de = parts
    return fields, body_en, body_de


def escape(text):
    return html.escape(text, quote=False)


def js_string(text):
    """Quote a string as a single-quoted JS string literal for js/i18n.js."""
    escaped = text.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return "'" + escaped + "'"


def render_inline(text):
    """Escape HTML, then apply the supported inline Markdown: **bold**,
    *italic*, and [link text](url). External links (http/https) open in a
    new tab automatically."""
    text = escape(text)

    def link_sub(m):
        label, url = m.group(1), m.group(2)
        target = ' target="_blank" rel="noreferrer"' if url.startswith(("http://", "https://")) else ""
        return f'<a href="{url}"{target}>{label}</a>'

    text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", link_sub, text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    return text


IMAGE_LINE_RE = re.compile(r"^!\[([^\]]*)\]\(([^)\s]+)\)$")


def render_body(markdown_body, filename, lang_label):
    """Markdown body -> (list of HTML block strings, word count)."""
    blocks = re.split(r"\n\s*\n", markdown_body.strip())
    html_blocks = []
    word_count = 0

    for block in blocks:
        block = block.strip()
        if not block:
            continue
        lines = block.splitlines()

        if all(line.startswith(">") for line in lines):
            quote_text = " ".join(line.lstrip(">").strip() for line in lines)
            word_count += len(quote_text.split())
            html_blocks.append(f'      <blockquote class="post-quote">{render_inline(quote_text)}</blockquote>')
            continue

        img_match = IMAGE_LINE_RE.match(block) if len(lines) == 1 else None
        if img_match:
            alt, src = img_match.group(1), img_match.group(2)
            caption = f"\n        <figcaption>{escape(alt)}</figcaption>" if alt else ""
            html_blocks.append(
                f'      <figure class="post-figure">\n'
                f'        <img src="{src}" alt="{escape(alt)}" loading="lazy">{caption}\n'
                f'      </figure>'
            )
            continue

        paragraph_text = " ".join(line.strip() for line in lines)
        word_count += len(paragraph_text.split())
        html_blocks.append(f"      <p>{render_inline(paragraph_text)}</p>")

    if not html_blocks:
        raise ValueError(f"{filename}: the {lang_label} body is empty.")
    return html_blocks, word_count


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

POST_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title_en} — Subhradip Roy</title>
<meta name="description" content="{lede_en_plain}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="../../css/style.css">
<noscript><style>[data-reveal="scramble"]{{visibility:visible}}</style></noscript>
<link rel="icon" type="image/png" href="../../favicon.png">
<link rel="apple-touch-icon" href="../../favicon.png">
</head>
<body>
<!-- AUTO-GENERATED by journal/build.py from journal/posts-md/{md_name}
     Do not hand-edit this file — edit the .md source and rerun the script. -->

<header class="site-header">
  <div class="header-status">
    <span class="status-dot" aria-hidden="true"></span>
    <span class="header-clock" data-clock>00:00:00</span>
    <span class="header-loc">IND — IST</span>
  </div>
  <nav class="site-nav">
    <a href="../../index.html" data-i18n="Index">Index</a>
    <a href="../../work/index.html" data-i18n="Work">Work</a>
    <a href="../../about.html" data-i18n="About">About</a>
    <a href="../../journal/index.html" aria-current="page" data-i18n="Journal">Journal</a>
    <a href="../../dump.html" data-i18n="Dump">Dump</a>
    <a href="../../contact.html" data-i18n="Contact">Contact</a>
  </nav>
  <div class="header-lang">
    <div class="lang-toggle">
      <button type="button" data-lang-btn="en" aria-current="true">EN</button>
      <button type="button" data-lang-btn="de" aria-current="false">DE</button>
    </div>
  </div>
</header>

<main>
  <article class="post-article">
    <a class="back-link" href="../index.html" data-i18n="← Journal">← Journal</a>
    <div class="post-meta-row"><span>{date_display}</span><span data-i18n="{read_en}">{read_en}</span></div>
    <h1 class="h-decode h-post" data-reveal="scramble" data-i18n="{title_en}">{title_en}</h1>
{cover_html}    <div data-lang-block="en">
      <p class="post-lede">{lede_en_html}</p>
{body_en_html}
    </div>
    <div data-lang-block="de">
      <p class="post-lede">{lede_de_html}</p>
{body_de_html}
    </div>

    <div class="post-footer">
      <span class="post-byline">Subhradip Roy</span>
      <a class="btn btn-secondary" href="mailto:subhrastien@gmail.com" data-i18n="Reply by email →">Reply by email →</a>
    </div>
  </article>
</main>

<footer class="site-footer is-dark">
  <div class="footer-top">
    <div>
      <h2 class="footer-statement" data-i18n="Let's build something that holds up.">Let's build something that holds up.</h2>
      <div class="btn-row">
        <a class="btn btn-primary-dark" href="mailto:subhrastien@gmail.com" data-i18n="Email me">Email me</a>
        <a class="btn btn-secondary-dark" href="https://calendly.com/subhradip_roy/15-minutes-short-call" target="_blank" rel="noreferrer" data-i18n="Book a call ↗">Book a call ↗</a>
      </div>
    </div>
    <div class="footer-col">
      <span class="footer-col-label" data-i18n="Pages">Pages</span>
      <a href="../../index.html" data-i18n="Index">Index</a>
      <a href="../../work/index.html" data-i18n="Work">Work</a>
      <a href="../../about.html" data-i18n="About">About</a>
      <a href="../../journal/index.html" data-i18n="Journal">Journal</a>
      <a href="../../dump.html" data-i18n="Dump">Dump</a>
      <a href="../../contact.html" data-i18n="Contact">Contact</a>
    </div>
    <div class="footer-col">
      <span class="footer-col-label" data-i18n="Elsewhere">Elsewhere</span>
      <a href="https://x.com/theroyprojects" target="_blank" rel="noreferrer">X ↗</a>
      <a href="https://www.linkedin.com/in/subhradip-roy/" target="_blank" rel="noreferrer">LinkedIn ↗</a>
      <a href="https://www.upwork.com/freelancers/~01828a5ece6eb825db" target="_blank" rel="noreferrer">Upwork ↗</a>
      <a href="https://contra.com/theroyproject" target="_blank" rel="noreferrer">Contra ↗</a>
    </div>
  </div>
  <div class="footer-bottom">
    <span>© 2026 Subhradip Roy</span>
    <span data-i18n="Top 1% — Upwork &amp; Contra">Top 1% — Upwork &amp; Contra</span>
  </div>
</footer>

<script src="../../js/main.js"></script>
<script src="../../js/i18n.js"></script>
</body>
</html>
"""

INDEX_ROW_TEMPLATE = """    <a class="journal-row" href="posts/{slug}.html" data-reveal="up"{delay_attr}>
      <span class="journal-row-date">{date_display}</span>
      <div>
        <h2 data-i18n="{title_en}">{title_en}</h2>
        <p data-i18n="{lede_en_plain}">{lede_en_plain}</p>
      </div>
      <span class="journal-row-read" data-i18n="{read_en}">{read_en}</span>
    </a>"""

START_MARK = "<!-- BUILD:POSTS:START (auto-generated by journal/build.py — do not hand-edit below) -->"
END_MARK = "<!-- BUILD:POSTS:END -->"
JS_START_MARK = "/* BUILD:JOURNAL:START (auto-generated by journal/build.py — do not hand-edit below) */"
JS_END_MARK = "/* BUILD:JOURNAL:END */"


# ---------------------------------------------------------------------------
# Build one post
# ---------------------------------------------------------------------------

class Post:
    def __init__(self, md_path):
        stem = md_path.stem  # e.g. 2026-08-19-my-new-post
        m = FILENAME_RE.match(stem)
        if not m:
            raise ValueError(
                f"{md_path.name}: filename must start with YYYY-MM-DD- "
                f"(e.g. 2026-08-19-my-new-post.md). See journal-guide.md."
            )
        year, month, day, _slug_tail = m.groups()
        self.slug = stem
        self.sort_key = (year, month, day)
        self.date_display = f"{day}.{month}.{year[2:]}"
        self.md_name = md_path.name

        fields, body_en, body_de = parse_front_matter(md_path.read_text(encoding="utf-8"), md_path.name)
        for required in ("title", "lede", "title_de", "lede_de"):
            if required not in fields or not fields[required]:
                raise ValueError(
                    f"{md_path.name}: front matter is missing '{required}:' — "
                    f"every post needs English AND German title/lede. See journal-guide.md."
                )

        self.title_en = fields["title"]
        self.title_de = fields["title_de"]
        self.lede_en_plain = fields["lede"]
        self.lede_de_plain = fields["lede_de"]
        self.lede_en_html = render_inline(self.lede_en_plain)
        self.lede_de_html = render_inline(self.lede_de_plain)
        self.cover = fields.get("cover", "").strip()
        self.cover_alt = fields.get("cover_alt", self.title_en).strip()

        self.body_en_blocks, words_en = render_body(body_en, md_path.name, "English")
        self.body_de_blocks, words_de = render_body(body_de, md_path.name, "German")

        words_en += len(self.title_en.split()) + len(self.lede_en_plain.split())
        words_de += len(self.title_de.split()) + len(self.lede_de_plain.split())
        auto_read_en = max(1, round(words_en / WORDS_PER_MINUTE))
        auto_read_de = max(1, round(words_de / WORDS_PER_MINUTE))
        self.read_en = fields.get("read", "").strip() or f"{auto_read_en} min"
        self.read_de = fields.get("read_de", "").strip() or f"{auto_read_de} Min."

    def cover_html(self):
        if not self.cover:
            return ""
        return (f'    <div class="post-cover"><img src="{self.cover}" '
                f'alt="{escape(self.cover_alt)}" loading="lazy"></div>\n')

    def render_page(self):
        return POST_TEMPLATE.format(
            title_en=escape(self.title_en),
            lede_en_plain=escape(self.lede_en_plain),
            lede_en_html=self.lede_en_html,
            lede_de_html=self.lede_de_html,
            date_display=self.date_display,
            read_en=escape(self.read_en),
            md_name=self.md_name,
            cover_html=self.cover_html(),
            body_en_html="\n".join(self.body_en_blocks),
            body_de_html="\n".join(self.body_de_blocks),
        )

    def render_index_row(self, delay_seconds):
        delay_attr = f' style="transition-delay:{delay_seconds:.2f}s"' if delay_seconds else ""
        return INDEX_ROW_TEMPLATE.format(
            slug=self.slug,
            date_display=self.date_display,
            title_en=escape(self.title_en),
            # Plain text on purpose (not lede_en_html): data-i18n only swaps
            # textContent, so any **bold**/[link](...) formatting would be
            # lost on toggle anyway — keep the listing preview formatting-free
            # so what you see in EN matches what you get in DE.
            lede_en_plain=escape(self.lede_en_plain),
            read_en=escape(self.read_en),
            delay_attr=delay_attr,
        )

    def dict_entries(self):
        """(english, german) pairs this post contributes to js/i18n.js."""
        pairs = [(self.title_en, self.title_de), (self.lede_en_plain, self.lede_de_plain)]
        if self.read_en != self.read_de:
            pairs.append((self.read_en, self.read_de))
        return pairs


def main():
    if not SRC_DIR.exists():
        sys.exit(f"No {SRC_DIR} folder found — nothing to build.")

    md_files = sorted(SRC_DIR.glob("*.md"))
    posts = []
    for md_path in md_files:
        try:
            posts.append(Post(md_path))
        except ValueError as e:
            sys.exit(f"ERROR — {e}")

    # Newest first, matching the site's existing convention.
    posts.sort(key=lambda p: p.sort_key, reverse=True)

    if not posts:
        print("No .md files in journal/posts-md/ yet — nothing to generate.")

    # --- write/refresh each post page -------------------------------------
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    wanted_files = {f"{p.slug}.html" for p in posts}
    written, updated = [], []
    for post in posts:
        out_path = OUT_DIR / f"{post.slug}.html"
        new_content = post.render_page()
        if out_path.exists() and out_path.read_text(encoding="utf-8") == new_content:
            continue
        is_new = not out_path.exists()
        out_path.write_text(new_content, encoding="utf-8")
        (written if is_new else updated).append(post.slug)

    # --- delete generated pages with no matching .md source ----------------
    deleted = []
    for existing in OUT_DIR.glob("*.html"):
        if existing.name not in wanted_files:
            existing.unlink()
            deleted.append(existing.name)

    # --- rewrite the listing on journal/index.html --------------------------
    index_html = INDEX_FILE.read_text(encoding="utf-8")
    if START_MARK not in index_html or END_MARK not in index_html:
        sys.exit(
            f"Couldn't find the {START_MARK!r} / {END_MARK!r} markers in "
            f"{INDEX_FILE} — has the file been hand-edited? Restore the "
            f"markers around the post list and rerun."
        )
    rows = "\n".join(
        post.render_index_row(min(i * 0.08, 0.4)) for i, post in enumerate(posts)
    )
    new_section = f"{START_MARK}\n{rows}\n{END_MARK}" if rows else f"{START_MARK}\n{END_MARK}"
    index_html = re.sub(
        re.escape(START_MARK) + r".*?" + re.escape(END_MARK),
        lambda _m: new_section,
        index_html,
        flags=re.S,
    )
    INDEX_FILE.write_text(index_html, encoding="utf-8")

    # --- rewrite the auto-managed section of js/i18n.js ---------------------
    i18n_js = I18N_FILE.read_text(encoding="utf-8")
    if JS_START_MARK not in i18n_js or JS_END_MARK not in i18n_js:
        sys.exit(
            f"Couldn't find the journal dictionary markers in {I18N_FILE} — "
            f"has the file been hand-edited? Restore\n  {JS_START_MARK}\n  {JS_END_MARK}\n"
            f"(as a pair, inside the DICT object) and rerun."
        )
    seen = {}
    lines = []
    for post in posts:
        for en, de in post.dict_entries():
            if en in seen and seen[en] != de:
                print(f"  WARNING: '{en}' maps to two different German translations "
                      f"across posts — keeping the first one seen.")
                continue
            if en in seen:
                continue
            seen[en] = de
            lines.append(f"    {js_string(en)}: {js_string(de)},")
    js_section = JS_START_MARK + ("\n" + "\n".join(lines) if lines else "") + "\n    " + JS_END_MARK
    i18n_js = re.sub(
        re.escape(JS_START_MARK) + r".*?" + re.escape(JS_END_MARK),
        lambda _m: js_section,
        i18n_js,
        flags=re.S,
    )
    I18N_FILE.write_text(i18n_js, encoding="utf-8")

    # --- summary -------------------------------------------------------------
    print(f"Built {len(posts)} post(s) from {SRC_DIR.relative_to(SITE)}/")
    if written:
        print(f"  new:      {', '.join(written)}")
    if updated:
        print(f"  updated:  {', '.join(updated)}")
    if deleted:
        print(f"  deleted:  {', '.join(deleted)}")
    if not (written or updated or deleted):
        print("  everything already up to date.")
    print(f"journal/index.html post list refreshed ({len(posts)} entries).")
    print(f"js/i18n.js journal dictionary refreshed ({len(lines)} translated strings).")


if __name__ == "__main__":
    main()
